# This config file for Travis CI
sudo: required

language: generic

services:
  - docker

git:
  quiet: true
  submodules: false

notifications:
  email:
    on_success: never
    on_failure: never

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=crs.rosinstall
    - ROS_REPO=ros
    - NOT_TEST_INSTALL=true
    - CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug"
    - ROSDEP_SKIP_KEYS="catkin ompl descartes_tesseract"

jobs:
  include:
    - os: linux
      dist: bionic
      language: cpp
      env:
      - ROS_DISTRO="dashing"
      - CLANG_FORMAT_CHECK=file
      - CLANG_FORMAT_VERSION=8
      - AFTER_SCRIPT=""
      - BADGE=clang-format
      cache:
        directories:
          - $HOME/.ccache
    - os: linux
      dist: bionic
      language: cpp
      env:
      - ROS_DISTRO="dashing"
      - NOT_TEST_BUILD=true
      - BEFORE_INIT="apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654"
      - BADGE=dashing

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master

script:
  - .industrial_ci/travis.sh
